# Pre-commit hooks for Easy PMF
# Install with: pip install pre-commit && pre-commit install

repos:
  # Use uv to run ruff directly from our project environment
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff lint
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        require_serial: false
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: false

  # Use uv to run mypy from our project environment
  - repo: local
    hooks:
      - id: mypy
        name: mypy type checking
        entry: uv run mypy
        language: system
        types: [python]
        require_serial: false

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check YAML files for parseable syntax
      - id: check-yaml
      # Check TOML files for parseable syntax
      - id: check-toml
      # Check JSON files for parseable syntax
      - id: check-json
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace
      - id: trailing-whitespace

# Configure which files to check
exclude: |
  (?x)^(
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    __pycache__/|
    build/|
    dist/|
    site/|
    htmlcov/|
    \.venv/|
    venv/
  )

# Global settings
default_language_version:
  python: python3.13

# Performance settings
fail_fast: false
minimum_pre_commit_version: "3.0.0"
