name: Bug Report
description: Report a bug or unexpected behavior
title: "🐛 [Bug]: "
labels: ["bug"]
assignees: ["gerritjandebruin"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: input
    id: version
    attributes:
      label: Easy PMF Version
      description: What version of Easy PMF are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe what happened..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load data with '...'
        2. Run PMF with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        from easy_pmf import PMF
        
        # Your code here that reproduces the issue
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: If applicable, include the full error message and traceback
      render: text
      placeholder: "Paste the error message here..."
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., Windows 11, macOS 13.0, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.11.5"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List relevant package versions (you can use `pip list` or `uv pip list`)
      render: text
      placeholder: |
        numpy==1.24.0
        pandas==2.0.0
        matplotlib==3.7.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, data files, etc.)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am using the latest version of Easy PMF
          required: false
