name: Feature Request
description: Suggest an idea or new feature for Easy PMF
title: "✨ [Feature]: "
labels: ["enhancement"]
assignees: ["gerritjandebruin"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."
    validations:
      required: false

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: "This feature would help me..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If possible, provide an example of how you would use this feature
      render: python
      placeholder: |
        # Example of how the feature might work
        pmf = PMF()
        pmf.new_feature(parameter="value")
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my work"
        - "Critical - Blocking my work"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple - Small change or addition"
        - "Medium - Moderate development effort"
        - "Complex - Significant development effort"
        - "Not sure"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature would benefit the general user base, not just my specific use case
          required: true
        - label: I would be willing to help test this feature if implemented
          required: false
        - label: I would be willing to contribute to the implementation
          required: false
