name: Other
description: Other issues not covered by the templates above
title: "📝 "
labels: ["triage"]
assignees: ["gerritjandebruin"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your issue below. If it could fit into one of the other templates (Bug Report, Feature Request, Question), please use those instead.

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please describe your issue in detail
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information that might be helpful
    validations:
      required: false
